

eureka:
  instance:
    hostname: localhost
    statuspageUrl: http://localhost:8001/index
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: spring-project-test-8001
server:
  port: 8001



security:
  oauth2:
    resource:
      id: spring-project-test-8001
      user-info-uri: http://localhost:8762/auth/api/member
      prefer-token-info: false
